### ISSUE TITLE
Where is my output?

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [apeltzer/MTNucRatioCalculator#3]
Thanks for the tool!

When I run:
`java -jar MTNucRatioCalculator-0.5.jar /vol/atac-seq/bwa/dm6-GSM2811118.samtools-coordinate.bam test.txt chrM`

Then the program takes a couple minutes, but no file appears... What am I doing wrong?

**Comment by Maarten-vd-Sande** [comment]
Also when I try it with the conda version:

`mtnucratio /vol/atac-seq/bwa/dm6-GSM2811118.samtools-coordinate.bam test.txt chrM`

**Comment by apeltzer** [comment]
Hi Maarten!

thanks for trying this out - the tool should actually produce a file like [this one](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/mtnucratio/filebam.mtnuc.json) in the folder the tool is created.

Can you also try to specify the MT name with extra `""`? 

`java -jar MTNucRatioCalculator-0.5.jar /vol/atac-seq/bwa/dm6-GSM2811118.samtools-coordinate.bam . "chrM"` should work for example and produce such a JSON output file.

**Comment by apeltzer** [comment]
Let me know if that worked for you!

**Comment by Maarten-vd-Sande** [comment]
Thanks for your reply!

I tried with the conda installed one:

    mtnucratio /vol/atac-seq/bwa/dm6-GSM2811118.samtools-coordinate.bam . "chrM"

But that didnt give output either.

**Comment by Maarten-vd-Sande** [comment]
> in the folder the tool is created.

So not from the folder the tool is executed?

**Comment by Maarten-vd-Sande** [comment]
I'll try to compile the program see if that works

**Comment by Maarten-vd-Sande** [comment]
Okay while playing around I found where the files went! Seems like the command ignores the path:
`/vol/atac-seq/bwa/dm6-GSM2811118.samtools-coordinate.bam.mtnucratiomtnuc.json`

And this is a complete json. This behaviour is fine by me, but maybe then the command print should be updated :angel: .

Thanks for your help!!

**Comment by apeltzer** [comment]
I agree ☝️ will keep this open to do that and keep track until then - thanks for your feedback !

**Comment by apeltzer** [comment]
Version 0.6. has a proper CLI that doesn't pretend you can actually configure where to store the output data anymore.

**Comment by Maarten-vd-Sande** [comment]
Cool, thanks!
